---
title: notice_error (PythonエージェントAPI)
type: apiDoc
shortDescription: Pythonの例外の詳細をエラーとして記録します。
tags:
  - Agents
  - Python agent
  - Python agent API
metaDescription: 'Python API: This call records the details of a Python exception as an error.'
translationType: machine
---

## 構文

```py
newrelic.agent.notice_error(error=None, attributes={}, expected=None, ignore=None, status_code=None, application=None)
```

Pythonの例外の詳細をエラーとして記録します。

## 説明

デフォルトでは、Pythonエージェントは未処理の例外のみを報告します。 `notice_error`を使用して、Python例外をエラーとして記録します。これは、UIで確認できます。パラメーターが指定されていない場合、現在処理されている例外の詳細が使用されます。

[トランザクションごとに最大5つの異なる例外を記録することができます。](/docs/accounts-partnerships/education/getting-started-new-relic/glossary#transaction) また、 [ハーベストサイクルごとにすべてのトランザクションの合計で最大20の例外を記録することができます。](/docs/apm/new-relic-apm/getting-started/glossary#harvest-cycle) 。

監視対象のWeb要求またはバックグラウンドタスクのコンテキスト内で`notice_error()`が呼び出されると、要求またはタスクが報告されているアプリケーションに対して例外の詳細が報告されます。

監視対象のWeb要求またはバックグラウンドタスクのコンテキスト外で呼び出された場合、 [`application`](/docs/agents/python-agent/python-agent-api/application)キーワード引数が指定され、例外が記録されるアプリケーションに対応するアプリケーションオブジェクトが指定されない限り、呼び出しは無視されます。 `newrelic.agent.application()`関数を使用して、適切なアプリケーションオブジェクトを取得できます。

## パラメーター

<Callout variant="tip">
  ほとんどすべての場合、 `notice_error`はパラメータを必要としません。
</Callout>

<table>
  <thead>
    <tr>
      <th width="25%">
        パラメータ
      </th>

      <th>
        説明
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `error`

        _タプル_
      </td>

      <td>
        オプションですが、ほとんど使用されません。 [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info)から返された例外情報 `(exception_class, exception_instance, traceback)` を含むタプル。
      </td>
    </tr>

    <tr>
      <td>
        `attributes`

        _ディクト_
      </td>

      <td>
        オプションです。エラーイベントに追加するカスタム属性（トランザクションに既に追加されているカスタム属性に加えて）。 [ハイセキュリティモード](/docs/agents/manage-apm-agents/configuration/high-security-mode) が有効になっている場合、これは機能しません。
      </td>
    </tr>

    <tr>
      <td>
        `expected`

        _boolean_、 _iterable\[String]_、 _callable(exception_class, exception_instance, traceback)->boolean_
      </td>

      <td>
        オプション。期待どおりにマークするエラーは、 `module:class`の形式の反復可能な文字列として渡すことができます。この値は、呼び出し可能またはエラーが予期されるかどうかを示すブール値にすることもできます。これらのエラーはUIに報告されますが、Apdexスコアやエラー率には影響しません。
      </td>
    </tr>

    <tr>
      <td>
        `ignore`

        _boolean_、 _iterable\[String]_、 _callable(exception_class_、 _exception_instance, traceback)->boolean_
      </td>

      <td>
        オプション。無視するエラーは、 `module:class`の形式の反復可能な文字列として渡すことができます。この値は、呼び出し可能またはエラーを無視するかどうかを示すブール値にすることもできます。特定の種類の例外を常に無視し、記録しないようにする必要がある場合に便利です。
      </td>
    </tr>

    <tr>
      <td>
        `status_code`

        _string_、 _integer_、 _callable(例外クラス、例外インスタンス、トレースバック)_
      </td>

      <td>
        オプション。例外ステータス コード。この値は、文字列、整数、または [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info) から返された例外情報 `(exception_class, exception_instance, traceback)` を受け取り、ステータス コードを整数として返す呼び出し可能なものにすることができます。
      </td>
    </tr>

    <tr>
      <td>
        `application`

        _アプリケーションオブジェクト_
      </td>

      <td>
        オプション。監視対象のWeb要求またはバックグラウンドタスクのコンテキスト外で呼び出された場合、 [`application`オブジェクト](/docs/agents/python-agent/python-agent-api/application)が提供されない限り、呼び出しは無視されます。
      </td>
    </tr>
  </tbody>
</table>

## 戻り値

なし。

## 例

### 例外の報告の簡単な例 [#simple-example]

大半の場合、パラメータを渡す必要はありません。例外を報告したい場所で次のように呼べばよいのです。

```py
newrelic.agent.notice_error()
```

### booleanを使った例 [#boolean-example]

ブール値を使用した`notice_error`の例。これは、エラーが予想されることを示しています。

```py
newrelic.agent.notice_error(expected=True)
```

### sys.exc_info()タプルと追加パラメータを用いたコール [#complex-example]

`sys.exc_info()`データを使用した`notice_error`の例：

```py
def complex_ignore_errors(exc, val, tb):
   # do some logic here
   return False

newrelic.agent.notice_error(attributes={'my_special_exception': True}, ignore=complex_ignore_errors)
```

### コールバックの使用例 [#callback-example]

特定の例外タイプの属性に基づいて例外を動的にフィルタリングする必要がある場合は、コールバック関数を指定できます。

```py
def _ignore_errors(exc, value, tb):
    if instance(value, HTTPError):
        if value.status == 404:
            return True

newrelic.agent.notice_error(ignore=_ignore_errors)
```

例外を無視するか期待する場合は、呼び出し可能オブジェクトの戻り値を `True`に設定します。他のチェックに関係なく、例外が決して無視されない/予期される場合は `False` を返し、後続のチェックと組み込みルールによって例外が無視される/予期されるかどうかを決定する必要がある場合は `None` を返します。コールバックは通常、 `True` または `None`を返します。