---
title: set_error_group_callback (Python エージェント API)
type: apiDoc
shortDescription: このメソッドを使用すると、エラー インボックス内のエラー グループを特定の識別子に設定できます。
tags:
  - Agents
  - Python agent
  - Python agent API
metaDescription: 'Python API: Used for implementing error groups.'
translationType: machine
---

## 構文 [#syntax]

```py
newrelic.agent.set_error_group_callback(callback_function(exc))
```

このメソッドを使用すると、エラー インボックス内のエラー グループを特定の識別子 (または「フィンガープリント」) に設定できます。

## 要件 [#requirements]

Python エージェント バージョン 8.8.0 以降。

## 説明 [#description]

このエンドポイントは、エラー グループの登録に使用されるコールバックという 1 つの入力を受け取ります。このコールバックは顧客定義であり、エージェントの [`notice_error` API](/docs/agents/python-agent/python-agent-api/noticeerror-python-agent-api)をトリガーした例外を受け入れる必要があります。この設定を解除するには、API を再度呼び出して、コールバックを `None`に設定します。

## パラメータ `set_error_group_callback` [#parameters-set-error-group-callback]

<table>
  <thead>
    <tr>
      <th width="25%">
        パラメータ
      </th>

      <th>
        説明
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `callback`

        _呼び出し可能な関数_
      </td>

      <td>
        必要。定義するコールバック関数。 `None` を使用して設定を解除します。
      </td>
    </tr>

    <tr>
      <td>
        `application`

        _アプリケーション インスタンス_
      </td>

      <td>
        オプション。アプリケーション インスタンスが提供されていない場合、関数はアクティブ化されたアプリケーション インスタンスをチェックします。
      </td>
    </tr>
  </tbody>
</table>

## 顧客定義のコールバック関数のパラメーター [#parameters-customer-defined-callback-function]

<table>
  <thead>
    <tr>
      <th width="25%">
        パラメータ
      </th>

      <th>
        説明
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `exception`

        _ランタイム例外_
      </td>

      <td>
        必要。これは、エージェントの [`notice_error` API](/docs/agents/python-agent/python-agent-api/noticeerror-python-agent-api)をトリガーしたランタイム例外です。
      </td>
    </tr>
  </tbody>
</table>

## 戻り値 [#return-values]

成功すると、API は目的のエラー グループ名を表す文字列をエージェント属性として追加します。

失敗した場合、API はエージェント属性として `error.group.name` を追加しません。

## 使用例 [#examples]

### エラーグループのコールバックを設定 [#error-group-callback-example]

`set_error_group_callback`の使用例:

```py
def customer_callback(exc):
    if isinstance(exc,ValueError):
        return "group1"


def some_other_function():
    try:
        raise ValueError("Oh no!")
    except Exception:
       newrelic.agent.notice_error()


def example_function(customer_callback):
    try:
        newrelic.agent.set_error_group_callback(customer_callback)
        some_other_function()
    finally:
        newrelic.agent.set_error_group_callback(None)
```