---
title: record_exception (Python API d'agent)
type: apiDoc
shortDescription: Enregistre les détails d'une exception Python en tant qu'erreur.
tags:
  - Agents
  - Python agent
  - Python agent API
metaDescription: 'Python API: This call records the details of a Python exception as an error.'
freshnessValidatedDate: never
translationType: machine
---

## Syntaxe

```py
newrelic.agent.record_exception(exc=None, value=None, tb=None, params={}, ignore_errors=[], application=None)
```

Cette API est obsolète. Veuillez utiliser [`notice_error()`](/docs/agents/python-agent/python-agent-api/notice_error).

## Description

Enregistre les détails d&apos;une exception Python en tant qu&apos;erreur.

Par défaut, l&apos;agent Python signale uniquement les exceptions non gérées. Utilisez `record_exception` pour enregistrer toute Python exception en tant qu’erreur, qui peut ensuite être trouvée dans l’ New Relic UI. Si aucun paramètre n&apos;est fourni, les détails de l&apos;exception en cours de traitement seront utilisés.

Vous pouvez enregistrer jusqu&apos;à cinq exceptions distinctes par [transaction](/docs/accounts-partnerships/education/getting-started-new-relic/glossary#transaction) et jusqu&apos;à 20 exceptions au total pour toutes les transactions par [cycle de collecte](/docs/apm/new-relic-apm/getting-started/glossary#harvest-cycle).

Lorsque `record_exception()` est appelé dans le contexte d&apos;une demande Web de monitoring ou d&apos;une tâche en arrière-plan, les détails de l&apos;exception seront signalés par rapport à l&apos; application à laquelle la demande ou la tâche est signalée.

Si appelé en dehors du contexte d&apos;une requête Web de monitoring ou d&apos;une tâche d&apos;arrière-plan, l&apos;appel sera ignoré à moins que l&apos;argument de mot-clé [`application`](/docs/agents/python-agent/python-agent-api/application) ne soit fourni et qu&apos;un objet application correspondant à l&apos; application par rapport à laquelle l&apos;exception doit être enregistrée soit fourni. Un objet d&apos;application approprié peut être obtenu à l&apos;aide de la fonction `newrelic.agent.application()` .

## Paramètres

<Callout variant="tip">
  Dans presque tous les cas, `record_exception` ne nécessitera aucun paramètre.
</Callout>

<table>
  <thead>
    <tr>
      <th width="25%">
        paramètres
      </th>

      <th>
        Description
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `exc`

        *objet de classe*
      </td>

      <td>
        Facultatif et rarement utilisé. Le type d&apos;exception de l&apos;exception en cours de traitement (un objet de classe). L&apos;une des trois valeurs (`exc`, `value` et `tb`) renvoyées par [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info). Si vous souhaitez transmettre l&apos;un de ces paramètres, les trois doivent être définis et ne peuvent pas être définis sur `None`. Si vous ne transmettez qu&apos;une seule de ces valeurs, l&apos;appel ne fonctionnera pas.
      </td>
    </tr>

    <tr>
      <td>
        `value`

        *int, chaîne, autre*
      </td>

      <td>
        Facultatif et rarement utilisé. Le paramètre d&apos;exception. L&apos;une des trois valeurs (`exc`, `value` et `tb`) renvoyées par [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info). Si vous souhaitez transmettre l&apos;un de ces paramètres, les trois doivent être définis et ne peuvent pas être définis sur `None`. Si vous ne transmettez qu&apos;une seule de ces valeurs, l&apos;appel ne fonctionnera pas.
      </td>
    </tr>

    <tr>
      <td>
        `tb`

        *objet*
      </td>

      <td>
        Facultatif et rarement utilisé. Un objet de traceback qui encapsule la stack d’appels au point où l’exception s’est produite à l’origine. L&apos;une des trois valeurs (`exc`, `value` et `tb`) renvoyées par [`sys.exc_info()`](https://docs.python.org/2/library/sys.html#sys.exc_info). Si vous souhaitez transmettre l&apos;un de ces paramètres, les trois doivent être définis et ne peuvent pas être définis sur `None`. Si vous ne transmettez qu&apos;une seule de ces valeurs, l&apos;appel ne fonctionnera pas.
      </td>
    </tr>

    <tr>
      <td>
        `params`

        *dict*
      </td>

      <td>
        Facultatif. attribut personnalisé à ajouter à l&apos;événement d&apos;erreur (en plus de tout attribut personnalisé déjà ajouté à la transaction). Si [le mode haute sécurité](/docs/agents/manage-apm-agents/configuration/high-security-mode) est activé, cela ne fonctionnera pas.
      </td>
    </tr>

    <tr>
      <td>
        `ignore_errors`

        *chaîne*
      </td>

      <td>
        Facultatif. Les erreurs à ignorer peuvent être transmises sous la forme `module:class`. Utile lorsque certains types d&apos;exceptions doivent toujours être ignorés et jamais enregistrés.
      </td>
    </tr>

    <tr>
      <td>
        `application`

        *objet d&apos;application*
      </td>

      <td>
        Facultatif. Si appelé en dehors du contexte d&apos;une requête Web de monitoring ou d&apos;une tâche d&apos;arrière-plan, l&apos;appel sera ignoré à moins que l&apos; [objet`application` ](/docs/agents/python-agent/python-agent-api/application)ne soit fourni.
      </td>
    </tr>
  </tbody>
</table>

## Valeurs de retour

Aucun.

## Exemples

### Exemple simple de signalement d&apos;exceptions [#simple-example]

Dans la grande majorité des cas, vous n&apos;aurez pas besoin de passer de paramètres. Vous devez simplement appeler ce qui suit lorsque vous souhaitez signaler une exception :

```py
newrelic.agent.record_exception()
```

### Appel avec l&apos;uplet sys.exc\_info() et un paramètre supplémentaire [#complex-example]

Un exemple de `record_exception` utilisant les données `sys.exc_info()` :

```py
def complex_ignore_errors(exc, val, tb):
   # do some logic here
   return False

newrelic.agent.record_exception(params={'my_special_exception': True}, ignore_errors=complex_ignore_errors)
```

### Exemple d&apos;utilisation du rappel [#callback-example]

Si vous devez filtrer les exceptions de manière dynamique en fonction de l&apos;attribut d&apos;un type d&apos;exception spécifique, vous pouvez fournir une fonction de rappel :

```py
def _ignore_errors(exc, value, tb): 
    if instance(value, HTTPError): 
        if value.status == 404: 
            return True

newrelic.agent.record_exception(ignore_errors=_ignore_errors)
```

Si l&apos;exception doit être ignorée, définissez la valeur de retour de l&apos;appelable sur `True`. Renvoie `False` si l&apos;exception ne doit jamais être ignorée, quelles que soient les autres vérifications, et `None` si les vérifications ultérieures et les règles intégrées doivent déterminer si l&apos;exception doit être ignorée. Un rappel renverrait normalement soit `True` soit `None`.