---
title: set_error_group_callback (Python API d'agent)
type: apiDoc
shortDescription: Cette méthode permet de définir des groupes d'erreurs dans la boîte de réception des erreurs sur un identifiant spécifique.
tags:
  - Agents
  - Python agent
  - Python agent API
metaDescription: 'Python API: Used for implementing error groups.'
freshnessValidatedDate: never
translationType: machine
---

## Syntaxe [#syntax]

```py
newrelic.agent.set_error_group_callback(callback_function(exception, transaction_data))
```

Cette méthode permet de définir des groupes d&apos;erreurs dans la boîte de réception des erreurs sur un identifiant spécifique (ou « empreinte »).

## Exigences [#requirements]

Python agent version 8.8.0 ou supérieure.

## Description [#description]

Ce point de terminaison prend une seule entrée, un rappel, qui est utilisé pour enregistrer des groupes d&apos;erreurs. Ce rappel est défini par les clients et doit accepter l&apos;exception qui a déclenché agent [`notice_error` API](/docs/agents/python-agent/python-agent-api/noticeerror-python-agent-api)l&apos; de l&apos; . Pour désactiver ce paramètre, appelez à nouveau l’API et définissez le rappel sur `None`.

## paramètre pour `set_error_group_callback` [#parameters-set-error-group-callback]

<table>
  <thead>
    <tr>
      <th width="25%">
        paramètres
      </th>

      <th>
        Description
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `callback`

        *fonction appelable*
      </td>

      <td>
        Requis. La fonction de rappel que vous souhaitez définir. Utilisez `None` pour désactiver.
      </td>
    </tr>

    <tr>
      <td>
        `application`

        *instance d&apos;application*
      </td>

      <td>
        Facultatif. Si aucune instance d&apos;application n&apos;est fournie, la fonction vérifiera l&apos;instance d&apos;application activée.
      </td>
    </tr>
  </tbody>
</table>

## paramètre pour la fonction de rappel définie par les clients [#parameters-customer-defined-callback-function]

<table>
  <thead>
    <tr>
      <th width="25%">
        paramètres
      </th>

      <th>
        Description
      </th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        `exception`

        *Exception d&apos;exécution*
      </td>

      <td>
        Requis. Il s&apos;agirait de l&apos;exception d&apos;exécution qui a déclenché l&apos; [API`notice_error` ](/docs/agents/python-agent/python-agent-api/noticeerror-python-agent-api)de l&apos;agent.
      </td>
    </tr>

    <tr>
      <td>
        `transaction_data`

        *dictionnaire*
      </td>

      <td>
        Requis. Un dictionnaire de données de transaction capturées par l&apos;agent Python.
      </td>
    </tr>
  </tbody>
</table>

## Valeurs de retour [#return-values]

En cas de succès, l’API ajoutera une chaîne représentant le nom du groupe d’erreurs souhaité en tant qu’attribut d’agent.

En cas d’échec, l’API n’ajoutera pas `error.group.name` comme attribut d’agent.

## Exemple d&apos;utilisation [#examples]

### Définir le rappel du groupe d&apos;erreurs [#error-group-callback-example]

Un exemple d&apos;utilisation de `set_error_group_callback`:

```py
def customer_callback(exc, data):
    if isinstance(exc, ValueError):
        return "group1"


def some_other_function():
    try:
        raise ValueError("Oh no!")
    except Exception:
       newrelic.agent.notice_error()


def example_function(customer_callback):
    try:
        newrelic.agent.set_error_group_callback(customer_callback)
        some_other_function()
    finally:
        newrelic.agent.set_error_group_callback(None)
```