---
subject: Python agent
releaseDate: '2017-03-15'
version: 2.82.0.62
downloadLink: 'https://pypi.python.org/pypi/newrelic'
---

## Notes

This release of the Python agent improves our introductory support for Tornado 4 applications by adding [Cross Application Tracing](https://docs.newrelic.com/docs/apm/transactions/cross-application-traces/cross-application-tracing) for web transactions that are sent to a Tornado 4 application.

The agent can be installed using easy_install/pip/distribute via the [Python Package Index](https://pypi.python.org/pypi/newrelic) or can be downloaded directly from the New Relic [download site](https://download.newrelic.com/python_agent/release/).

## New Feature

* **Tornado 4 applications will now appear in Service Maps**

  Tornado 4 [Cross Application Tracing](https://docs.newrelic.com/docs/apm/transactions/cross-application-traces/cross-application-tracing) is now supported for inbound web transactions. In addition to Service Maps, the calling application's APM will now have links to the Tornado 4 application it called in the External Services tab and in Transaction Traces.

## Bug Fixes

* **Record exceptions outside of view handlers in Django 1.10**

  Unhandled exceptions that occurred outside of a view handler in Django 1.10 were not reported. In addition to middleware exceptions, these unhandled exceptions can be generated when a view handler returns a TemplateResponse and rendering that template would result in an exception.
* **Consistent WSGI/Application and WSGI/Response segments**

  Prior to this release, the agent would group segments under `WSGI/Application` and `WSGI/Response` differently, depending on whether or not [browser monitoring](https://newrelic.com/browser-monitoring) was enabled. This has now been made consistent.
* **Improved New Relic WSGI middleware behavior**

  The New Relic agent is now resilient when called by non-conforming middleware. Transactions will continue to be reported normally when the New Relic agent is called by WSGI middleware that does not call the close() method as described in the [PEP 333](https://www.python.org/dev/peps/pep-0333) specification.
