---
title: Python 에이전트 및 셀러리
tags:
  - Agents
  - Python agent
  - Back-end services
metaDescription: How to record Celery background processes using the Python agent.
translationType: machine
---

Celery를 분산 작업 대기열 시스템으로 사용하는 경우 Python 에이전트를 사용하여 Celery 프로세스를 [비웹 트랜잭션](/docs/apm/transactions/intro-transactions/monitor-background-processes-other-non-web-transactions)으로 기록할 수 있습니다.

Python 에이전트가 Celery와 함께 작동하도록 하려면 먼저 [에이전트 설치 지침](/docs/agents/python-agent/installation-and-configuration/python-agent-installation) 에 따라 에이전트를 설치, 구성 및 [테스트](/docs/agents/python-agent/installation-and-configuration/testing-python-agent) 하십시오. 그런 다음 이 Celery 관련 지침을 사용하십시오.

## 샐러리를 실행 [#running-with-celery]

에이전트와 함께 Celery를 실행하는 데 사용하는 명령은 Celery 버전 및 특정 설정에 따라 다릅니다.

<CollapserGroup>
  <Collapser
    id="run-celery-celery"
    title="셀러리"
  >
    `celery` 명령을 사용하는 경우 사용자 지정 옵션을 포함합니다.

    ```
    NEW_RELIC_CONFIG_FILE=/some/path/newrelic.ini newrelic-admin run-program celery YOUR_COMMAND_OPTIONS
    ```

    예를 들어:

    ```
    NEW_RELIC_CONFIG_FILE=/some/path/newrelic.ini newrelic-admin run-program celery -A tasks worker --loglevel=info
    ```
  </Collapser>

  <Collapser
    id="run-celery-celeryd"
    title="셀러리"
  >
    `celeryd` run 명령은 최신 Celery 릴리스에서 더 이상 사용되지 않습니다. 여전히 `celeryd` 을 사용하는 경우 사용자 지정 옵션을 포함합니다.

    ```
    NEW_RELIC_CONFIG_FILE=some/path/newrelic.ini newrelic-admin run-program celeryd YOUR_COMMAND_OPTIONS
    ```
  </Collapser>

  <Collapser
    id="run-celery-django"
    title="장고"
  >
    Django 관리 명령으로 Celery를 시작하는 경우 `manage.py` 을 사용합니다. `celery` 명령을 Django 명령으로 바꾸고 사용자 지정 옵션을 모두 포함합니다.

    ```
    NEW_RELIC_CONFIG_FILE=/some/path/newrelic.ini newrelic-admin run-program python manage.py celery YOUR_COMMAND_OPTIONS
    ```
  </Collapser>

  <Collapser
    id="run-celery-initd"
    title="초기화 스크립트"
  >
    Celery의 일반 초기화 스크립트 중 하나를 사용하는 경우 스크립트를 편집하고 스크립트가 사용될 때 호출되는 `celery` 명령을 래핑합니다. 이 명령은 일반적으로 다음과 같습니다.

    ```
    CELERY_BIN=${CELERY_BIN:-"celery"}
    ```

    에이전트의 래퍼 스크립트를 추가하려면 `CELERY_BIN` 변수를 다음으로 변경합니다. 여기서 `some/path/` 파일 또는 패키지의 실제 경로입니다.

    ```
    CELERY_BIN=${CELERY_BIN:-"NEW_RELIC_CONFIG_FILE=/some/path/newrelic.ini /some/path/bin/newrelic-admin run-program /some/path/bin/celery"}
    ```

    이 변경으로 `CELERY_BIN` 이 호출될 때마다 실제 `celery` 명령 주위에 에이전트 래퍼 스크립트와 함께 호출됩니다.
  </Collapser>
</CollapserGroup>

## 애플리케이션 이름 선택 [#selecting-the-application-name]

Python 에이전트 구성 파일의 `app_name` 설정은 New Relic UI에 표시되는 앱 이름을 설정합니다.

* Python 에이전트가 Celery 작업을 모니터링하고 `app_name` 을 애플리케이션 에이전트의 `app_name` 에 사용된 것과 동일한 값으로 설정하면 두 소스의 데이터가 해당 이름으로 UI에서 결합됩니다.
* 다른 이름을 설정하면 데이터가 두 개의 다른 이름으로 UI에 별도로 나타납니다.

[에이전트 구성 파일에 여러 앱 이름을 설정](/docs/agents/manage-apm-agents/app-naming/use-multiple-names-app) 하여 결합된 데이터와 분리된 데이터를 모두 모니터링할 수 있습니다. 다음은 Django 애플리케이션을 예로 사용하여 이를 수행하는 일반적인 방법입니다.

<CollapserGroup>
  <Collapser
    id="multiple-app-names"
    title="여러 애플리케이션 이름 사용"
  >
    Django 앱을 모니터링하는 에이전트의 경우 다음을 설정합니다.

    ```
    app_name = Your_app_name (Django); Your_app_name (Combined)
    ```

    Celery를 모니터링하는 에이전트의 경우 다음을 설정합니다.

    ```
    app_name = Your_app_name (Celery); Your_app_name (Combined)
    ```

    그 결과 UI에 세 개의 이름이 표시됩니다.

    * `Your_app_name (Combined)`, Celery와 Django 애플리케이션의 데이터를 결합합니다.
    * `Your_app_name (Django)`, Django 앱 데이터를 보여줍니다.
    * `Your_app_name (Celery)`, 셀러리 데이터를 보여줍니다.
  </Collapser>
</CollapserGroup>

## 작업 재시도 오류 무시 [#ignoring-task-retry-errors]

Celery를 사용할 때 작업이 실패하고 `celery.exceptions:Retry` 또는 `celery.exceptions:RetryTaskError` 예외가 발생할 수 있습니다. 예외는 사용되는 Celery 버전에 따라 다릅니다.

이러한 오류를 무시하려면 New Relic **Application 설정** UI 또는 에이전트 구성 파일에서 설정하십시오. UI 변경 사항은 [구성 우선 순위 규칙에 따라 구성](/docs/agents/python-agent/installation-configuration/python-agent-configuration#options) 파일 변경 사항을 재정의합니다.

UI에서 오류 무시 설정을 사용하려면:

1. **[one.newrelic.com](https://one.newrelic.com/all-capabilities)** 에서 **APM > (앱 선택) > Settings > Application**을 선택합니다 .
2. **서버 측 에이전트 구성을** 선택하십시오.
3. **오류 수집** 에서 무시할 오류를 쉼표로 구분하여 입력합니다.

에이전트 구성 파일을 사용하여 이러한 오류를 무시하려면 [`ignore_errors`](/docs/agents/python-agent/installation-configuration/python-agent-configuration#error-ignore) 설정과 공백으로 구분된 예외 목록을 사용하십시오.

```
error_collector.ignore_errors = celery.exceptions:Retry celery.exceptions:RetryTaskError
```

## 문제점 해결

Celery 작업자 프로세스가 갑자기 종료되면 에이전트는 정상적인 종료 프로세스를 완료할 수 없습니다. 즉, 최종 데이터 페이로드가 전송되지 않습니다. 그 결과 에이전트가 예상보다 적은 수의 Celery 트랜잭션을 보고하거나 트랜잭션이 전혀 보고되지 않습니다.

이는 풀 작업자 프로세스가 새 프로세스로 교체되기 전에 실행할 수 있는 최대 작업 수를 정의하는 `CELERYD_MAX_TASKS_PER_CHILD` 설정을 사용할 때 발생할 수 있습니다. 사용하면 해당 제한에 도달하면 작업자가 강제로 종료되므로 에이전트에서 데이터를 기록하지 않습니다. 예를 들어, `MAX_TASKS_PER_CHILD = 1` 인 경우 보고되는 데이터가 없습니다.

이 문제를 해결하는 방법은 애플리케이션에서 `MAX_TASKS_PER_CHILD` 제한을 사용하려는 이유에 따라 다릅니다.

* 정상적인 종료 프로세스를 허용하려면 이를 기본 무제한 설정으로 되돌립니다.
* 문제의 영향을 줄이려면 `MAX_TASKS_PER_CHILD` 제한을 높이십시오.

<Callout variant="important">
  버전 3.2.2.94 이상의 경우 `MAX_TASKS_PER_CHILD` 제한에 도달하면 Python 에이전트가 종료됩니다. 데이터가 손실되지 않습니다.
</Callout>

<Callout variant="important">
  Celery의 기본 프로세스 모니터링은 에이전트로는 불가능하며 작업자 프로세스만 모니터링할 수 있습니다. [응용 프로그램 경고 활성화를](/docs/apm/agents/python-agent/troubleshooting/activate-application-warning-python)참조하십시오.
</Callout>